# Generated by Django 3.0.7 on 2020-10-19 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cf', '0002_auto_20201019_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptedpath',
            name='filename',
        ),
        migrations.AddField(
            model_name='decryptedpath',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decryptedpath',
            name='fpath',
            field=models.FilePathField(path='media/decrypted/'),
        ),
        migrations.AlterField(
            model_name='encryptedpath',
            name='fpath',
            field=models.FilePathField(path='media/encrypted_file/'),
        ),
    ]
