# Generated by Django 3.0.7 on 2020-10-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0003_auto_20201019_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedpath',
            name='filename',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encryptedpath',
            name='filename',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decrypt',
            name='filename',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='decrypt',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='filename',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
