# Generated by Django 3.0.7 on 2020-10-21 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0004_auto_20201021_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decrypt',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='decrypt',
            name='password',
        ),
        migrations.RemoveField(
            model_name='encrypt',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='encrypt',
            name='password',
        ),
        migrations.AddField(
            model_name='decryptedpath',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='decryptedpath',
            name='password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encryptedpath',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='encryptedpath',
            name='password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
