# Generated by Django 3.0.7 on 2020-10-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0005_auto_20201021_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decryptedpath',
            old_name='date',
            new_name='ddate',
        ),
        migrations.RenameField(
            model_name='decryptedpath',
            old_name='filename',
            new_name='dfilename',
        ),
        migrations.RenameField(
            model_name='encryptedpath',
            old_name='date',
            new_name='edate',
        ),
        migrations.RenameField(
            model_name='encryptedpath',
            old_name='filename',
            new_name='efilename',
        ),
    ]
