# Generated by Django 3.0.7 on 2020-10-24 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0006_auto_20201021_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='decryptedpath',
            name='ddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='encryptedpath',
            name='edate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
