# Generated by Django 3.0.7 on 2020-10-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0007_auto_20201024_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encrypt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Decrypt',
        ),
        migrations.DeleteModel(
            name='Encrypt',
        ),
    ]
